#!/bin/sh -e

export DESTDIR="$1"
export CFLAGS="$CFLAGS -static"
export CXXFLAGS="$CXXFLAGS -static"
export LDFLAGS="$LDFLAGS -lc++ -lc++abi -lunwind -static"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_TESTING=OFF \
    -DZSTD_LIBRARY=/usr/lib/libzstd.a

cmake --build   build
cmake --install build

mkdir -p "$1/usr/lib/ccache/bin"
host=$(cc -dumpmachine)

for link in \
    cc  "$host-cc"  \
    clang "$host-clang" \
    clang++ "$host-clang++" \
    cpp "$host-cpp" \
    c++ "$host-c++"
do
    ln -sf /usr/bin/ccache "$1/usr/lib/ccache/bin/$link"
done
